{% set version = '0.1-42' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-slam
  version: {{ version|replace("-", "_") }}

source:
  fn: slam_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/slam_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/slam/slam_{{ version }}.tar.gz
  sha256: 7206b0189544c9878b83005f80f89626cc2c53cfe3e640aeaa9c3da1f07675df


  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('slam')"           # [not win]
    - "\"%R%\" -e \"library('slam')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=slam
  license: GPL-2
  summary: Data structures and algorithms for sparse arrays and matrices, based on index arrays
    and simple triplet representations, respectively.
  license_family: GPL2

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: slam
# Version: 0.1-42
# Title: Sparse Lightweight Arrays and Matrices
# Authors@R: c(person("Kurt", "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org", comment = c(ORCID = "0000-0003-4198-9911")), person("David", "Meyer", role = "aut"), person("Christian", "Buchta", role = "aut"))
# Description: Data structures and algorithms for sparse arrays and matrices, based on index arrays and simple triplet representations, respectively.
# Depends: R (>= 3.4.0)
# Imports: stats
# Enhances: Matrix, SparseM, spam
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2017-12-21 19:55:05 UTC; hornik
# Author: Kurt Hornik [aut, cre] (0000-0003-4198-9911), David Meyer [aut], Christian Buchta [aut]
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2017-12-21 20:58:52 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
