travis:
  secure:
    BINSTAR_TOKEN: DYRcebBjEuDllnmU2eTCYcDT79bNq2twyxvbM5DZjcdc1fQotpCT7bBaom3d+xTKrD8cWxHCjdRzzCpiPUXnTpHdONENYox5ROO1x9MPiwt2nmkhnSCpBTeKn4+d1/1cdVUe+GhvE8wem9uhqPEoCP/JjF1hqiRR2cJbjh8ECP+3uXLTlO2VNMz2pJNkXymorYvkl3F6+wlfL/C4uYd0Vmo2yj0IeH8VAdRzEaOtVqrBQ8RWOr+xm6XGkCA5cTDeoi7UaGf6VWPgS79kgEYk6hcZg0Xeeph5HbcshLKWzkYSkz94ounE+DX3Zhr6o7pewol7b3Q4v0Ho6cC6CM4AMvHtLcQCYysYYsHbqWgH62j41q+z9dsbMXmhXpZFhZyLk3nL7vhjQS+CHYW28titSRmWKKIcLrC/logdRJOcMEe3gWdPjRCjvObixH9ZcKbT4gcLd5ORqIr88IEvmKZwXmIgfnGsQhoC2ptnJx9H4+UY3p2wA4lb7dJPLGapWgd5HBRpFu1qYgeZmFBCB2lVEyC/wYpGoFc8KjOMb21pY7PY3jvLKhPut5f1xo+Yw6v+T3Gu1PQUWGPPMM5Bd6HDl57PMfcyWU9asxEGSNUEdfVOj877w/VGg97jIAim0RCzkqUgkAGs0WqAWZsHdImED0J+FHXz70OS3WaLQQd6jrY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
