travis:
  secure:
    BINSTAR_TOKEN: KSWsPZLs0C6ArPlRDkzWcsg3yKn1yHDd2em7f1xZDfMW0hz2eYWZfKmvwNjSjeSNHlofmn5zB5oTePiU6+A81NlyhFplcP31WFCSeIQr4nH1nq0eJ84vfXQgXUJ/rD7FUvbqrfOcGDddhD0P7cAvkmGMW/AGHNXlszPurbsRUajfspOPvCylDI2yUAxjGyt5pT+dVarEp4FhB1ITiCcw9Ym4DmkWRZVXd3Mb+jjrpphlzxpgRnV8LTf0cqF2d15kmaxYKgV3aE+9lkwerJ/YLmzrl977OB17NU2ziTZvDO7WHn8Gfmy8l/wS6paRGXSPwY5SqweBGh9g+WWWzHLnku5inSY5cLnVd61J/zKmNqn2q87+imxZvOXpGedwNM9P2DbySDmwri6MotiDyw1n5OE4Rq5ncHVrwZAIk8Dj85B8peVfMceE0f3IY73lA8hd2UtXgpMOe5Nm4eNlRSqgfYSrkblBS+Z8ugDp5jekkYJUrGnfcPmSl0lyTab+4B3d3NBK7CVkBjWw4M0wd2unsreoAp6hpQPyYGKGlAPcvJKo6LyOlGfKadGVeVgfgMmQVT3j9aWmnzF2g3xrfbvOC0OLm39P1E6Ll/3lMQUc5n+Oj1/sEmBgZEcULdxvF5W0WFD+K793ziLz6yq8thvuFUsD65MnqMsuvu2k7jbs4OY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
