travis:
  secure:
    BINSTAR_TOKEN: tGNwQ/II7jqy+kufE6RZ9DrLimgfUJvw8Q5WOCU3j4NVtXt2Dmp5uRg011mls3ogC5+w3DsqN85keNzPCOHgkPfVtpvobySOdO8+3OQZrr3BkXDC7a/HcYqUpkLgVPpABLmYlg0QVKhB3pYc06AHfAxSIie7t0y+5n1TWBBp5XWU5UWEF4iuifQIarDFYSjciob5+IywyfC8RvtPfWFjimLA9zXwesDoQduepkpuIERYmtvrBJgt/lqLqZswB/KJCgkOopI5TZgfeKvkd9VyT/99dpM8WU3XScPLj9gmBedE5Fx7XKC9f9dLZpwhfqnEEpmrYw24VAaripFLJlNmc3BITXkHSYVT64YcJMnFD7sCKSqZcl6RSuud5gtWTtqMcIczznFI1iGbENuPhfDcu3xyRXQu90nYeaQbZ4QAlxvslA+Ink7TtEy1jp96ALzqt9ZymF4+laJoqDQMfuZ23MJWCyOBU2FX2l1/yq2vLGa7NJGeTdD1niTaOK3U9BLmRxbvMamkEfuN40esml0KjeO2h8d605HB/oaQHeJAr8Z69ai0xnnyUMogRLcRqUF0yDiLj6an58i9ed5KVBdsT5oamPj4GTXKZqBJ50s2N4yhs/BWfO+BUZtTisc6dKDPgMj3YDU6/PWqatFyOuLzetd95KTQG81BHN/7qibYDwI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
